name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    - run: npm ci
    - run: ./mill fullLinkJS
    - run: npm run build --if-present
    - run: zip -r mpb.zip dist/
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: mpb.zip
        generate_release_notes: true
    - name: Upload to webstore   
      # https://github.com/fregante/chrome-webstore-upload-cli
      run: npx chrome-webstore-upload --source mpb.zip
      env:
        EXTENSION_ID: nojpfacijldambjcnpbpneghbaefnlme 
        CLIENT_ID: ${{ secrets.CLIENT_ID }} 
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }} 
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
